//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace laundry_1._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class detail_tm
    {
        public string no { get; set; }
        public string id_tm { get; set; }
        public string diskon { get; set; }
        public string nama_paket { get; set; }
        public string berat { get; set; }
        public string sub_total { get; set; }
    }
}
