//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace laundry_1._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class paket
    {
        public string id_paket { get; set; }
        public string nama_paket { get; set; }
        public Nullable<int> harga_satuan { get; set; }
        public Nullable<int> durasi { get; set; }
    }
}
