//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace laundry_1._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class transaksi_ambil
    {
        public string id_tp { get; set; }
        public string id_tm { get; set; }
        public string id_user { get; set; }
        public string id_pel { get; set; }
        public Nullable<System.DateTime> tgl_tp { get; set; }
        public Nullable<int> bayar_tp { get; set; }
    }
}
