//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace laundry_1._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public string id_user { get; set; }
        public string uname { get; set; }
        public string upass { get; set; }
        public string level { get; set; }
    }
}
